name: actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install Dependencies
        run:
          make install-deps

      - name: Analysing the code with pylint
        run:
          make lint

      - name: Test Project
        run:
          make test

      
